FROM python:3.11-slim
WORKDIR /code
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install streamlit
COPY ./streamlit_app_deploy.py /code/streamlit_app_deploy.py
CMD ["streamlit", "run", "streamlit_app_deploy.py", "--server.port", "8501", "--server.address", "0.0.0.0"]