"""add is_processed to answers

Revision ID: 77ed6d4e4a66
Revises: a0620647aeca
Create Date: 2026-05-05 13:11:30.603748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ed6d4e4a66'
down_revision: Union[str, Sequence[str], None] = 'a0620647aeca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('is_processed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'is_processed')
    # ### end Alembic commands ###
